spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cimpoiesu
    username: root
    password: example
  jpa:
    showSql: true
    hibernate:
      ddl-auto: create

#  data:
#    mongodb:
#      authentication-database=admin
#      username=rootuser
#      password=rootpass
#      database=cimpoiesudanila
#      port=27017
#      host=localhost

#spring.datasource.url: Это свойство определяет URL-адрес базы данных, к которой приложение будет подключаться.
#spring.datasource.username и spring.datasource.password: Эти свойства определяют учетные данные (имя пользователя и пароль) для подключения к базе данных.

#spring.jpa.showSql: Это свойство определяет, следует ли выводить SQL-запросы в консоль для отладки и мониторинга
#spring.jpa.hibernate.ddl-auto: Это свойство определяет стратегию автоматического создания схемы базы данных.